AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:
  EstimateUsageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ObjectLockEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - "x-amz-version-id"

  EstimateDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PnEstimate'
      AttributeDefinitions:
        - AttributeName: "paId"
          AttributeType: "S"
        - AttributeName: "referenceMonth"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "paId"
          KeyType: "HASH"
        - AttributeName: "referenceMonth"
          KeyType: "RANGE"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ActivityReportDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PnActivityReport'
      AttributeDefinitions:
        - AttributeName: "paId"
          AttributeType: "S"
        - AttributeName: "referenceMonth"
          AttributeType: "S"
        - AttributeName: "reportKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "paId"
          KeyType: "HASH"
        - AttributeName: "reportKey"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "INDEX_PA_REF_MONTH"
          KeySchema:
            - AttributeName: "paId"
              KeyType: "HASH"
            - AttributeName: "referenceMonth"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ProfilationDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-PnProfilation'
      AttributeDefinitions:
        - AttributeName: "paId"
          AttributeType: "S"
        - AttributeName: "referenceYear"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "paId"
          KeyType: "HASH"
        - AttributeName: "referenceYear"
          KeyType: "RANGE"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  EstimateUsageBucketName:
    Description: Name of s3 bucket
    Value: !Ref EstimateUsageBucket

  EstimateDynamoTableName:
    Description: Name of dynamodb table containing request
    Value: !Ref EstimateDynamoTable

  EstimateDynamoTableArn:
    Description: ARN of dynamodb table containing request
    Value: !Sub '${EstimateDynamoTable.Arn}'

  ProfilationDynamoTableName:
    Description: Name of dynamodb table containing request
    Value: !Ref ProfilationDynamoTable

  ProfilationDynamoTableArn:
    Description: ARN of dynamodb table containing request
    Value: !Sub '${ProfilationDynamoTable.Arn}'

  ActivityReportDynamoTableName:
    Description: Name of dynamodb table containing request
    Value: !Ref ActivityReportDynamoTable

  ActivityReportDynamoTableArn:
    Description: ARN of dynamodb table containing request
    Value: !Sub '${ActivityReportDynamoTable.Arn}'